chore(js-starter): Embed runtime into template
nitrictech/examples pull request #83
Opened 2024-10-31 23:57 UTC by tjholm

2024-11-01 00:05 UTC, HomelessDinosaur commented
Should update `helloApi` to `mainApi` for consistency with ts starter changes.

2024-11-01 00:46 UTC, davemooreuws requested changes, later dismissed

2024-11-01 00:46 UTC, davemooreuws commented on v1/javascript-starter/services/api.js
rename api to reflect ts changes

2024-11-01 01:39 UTC, tjholm commented on v1/javascript-starter/services/api.js
done

2024-11-01 04:20 UTC, davemooreuws approved these changes

2024-11-04 02:37 UTC, jyecusch approved these changes

2024-11-04 02:37 UTC, merged